### ISSUE TITLE
Unable to received email 

### ISSUE THREAD

**Issue by dkpant1982** [rajeshkrish12/AWS-Lambda_EC2-AMI-backups#1]
Hi Rajesh
this particular python script can take the AMI but unable to send the email notification. as i had tried number of time. i already mention the SNS  ARN into the script but that didn't work the SNS role also given to the lambda.
aws_sns_arn = os.getenv('arn:aws:sns:us-east-1:............', None)

Regards
DK

**Comment by rajeshkrish12** [comment]
Hi DK,

You don't need to add the SNS ARN in the script, Instead just add it as an environmental variable for the lambda function with the _key_ as **aws_sns_arn** and the _value_ with your **<SNS **ARN>.****

Let me know for further support or clarrifications.

Regards,
Rajesh K

**Comment by dkpant1982** [comment]
Hi Rajesh,

Thanks for the reply, Yesterday i had fix, it now i am receiving emails, but does that will also work when 
there is a failure in backup. and one more question for delete the AMI i have to put the second script in lambda so like i am taking backup of every Saturday so when i need to schedule for deleting AMI script.

i am using below fix
aws_sns_arn = 'arn:aws:sns:us-west-2:accountnumber:otherdetails of SNS arn"'

**Comment by rajeshkrish12** [comment]
DK,

The script only triggers the AMI creation it doesn't wait for any success response, so the mail just notifies the count of AMI creation.

AMI deleting works based on the retention period i.e by default the retention is 7,  you can add a tag and give the retention period in days count as you wish.

Regards,
Rajesh K
